# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #checkout repositry under directory
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    #Azure Cli login
    #- name: Login to Azure
    #  uses: azure/login@v1
    #  with:
     #   creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    #Build and push Docker images
    - name: Azure Docker Images login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
      docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nodejsactions:${{ github.sha }}
      docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nodejsactions:${{ github.sha }}
    
